SET SQL_SAFE_UPDATES = 0;
ALTER TABLE PESSOA_TURMA MODIFY COLUMN IDPESSOATURMA INT NOT NULL AUTO_INCREMENT;
ALTER TABLE PESSOA_AULA MODIFY COLUMN IDPESSOAAULA INT NOT NULL AUTO_INCREMENT;
ALTER TABLE USUARIO MODIFY COLUMN SENHA VARCHAR(100);   
ALTER TABLE PESSOA ADD COLUMN ARQUIVADO TINYINT(1);
UPDATE PESSOA SET ARQUIVADO = 0;
ALTER TABLE UNIDADE ADD COLUMN ARQUIVADO TINYINT(1);
UPDATE UNIDADE SET ARQUIVADO = 0;
ALTER TABLE CURSO ADD COLUMN ARQUIVADO TINYINT(1);
UPDATE CURSO SET ARQUIVADO = 0;

ALTER TABLE ESTAGIO ADD COLUMN ARQUIVADO TINYINT(1);
UPDATE ESTAGIO SET ARQUIVADO = 0;

ALTER TABLE TURMA ADD COLUMN ARQUIVADO TINYINT(1);
UPDATE TURMA SET ARQUIVADO = 0;
