alter table PESSOA_TURMA modify column IDPESSOATURMA int NOT NULL AUTO_INCREMENT;
alter table PESSOA_AULA modify column IDPESSOAAULA int NOT NULL AUTO_INCREMENT;
ALTER TABLE USUARIO MODIFY COLUMN SENHA VARCHAR(100);